BNF-1367 Rebrand
nice-digital/bnf-gatsby pull request #106
Opened 2022-07-20 15:57 UTC by barkertron

https://nicedigital.atlassian.net/browse/BNF-1367

2022-07-21 07:57 UTC, ediblecode requested changes

2022-07-21 07:57 UTC, ediblecode commented on gatsby/src/components/DrugSections/IndicationsAndDose/IndicationsAndDoseContent/IndicationsAndDoseContent.module.scss
> +      colours.$indication-dose-neonate-1,
Lovely

2022-07-21 07:57 UTC, ediblecode commented on gatsby/src/components/SiteDistinction/SiteDistinction.module.scss
> +    border-top-color: settings.$bnfc-brand-colour;
We might as well get rid of the settings file and move into the colour tokens file?

2022-07-21 07:57 UTC, ediblecode commented on gatsby/gatsby-ssr.tsx
> +				href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&family=Lora:ital,wght@0,400;0,600;1,400;1,600&display=swap"
Can get just use Lora 600 and not 400 please?

2022-07-21 07:57 UTC, ediblecode commented on gatsby/src/styles/_colours.scss
> +@use '@nice-digital/nds-core/scss/colours/tokens/global';
This file is glorious

2022-07-21 07:57 UTC, ediblecode commented on gatsby/gatsby-ssr.tsx
> +	components.push(
If we're changing our font loading mechanism from self-hosted with link preloads, then please could you remove the link headers from web.config as they're no longer needed?

2022-07-21 07:57 UTC, ediblecode commented on gatsby/src/styles/global.scss
>  @import '~@nice-digital/design-system/scss/base';
I don't think we need the ~ any more?

2022-07-21 07:57 UTC, ediblecode commented on gatsby/src/styles/global.scss
>  $nds-include-spacing-modifiers: false;
I think these variables have changed names, and can be configured with the import below so they're like:

```
@use '@nice-digital/design-system/scss/base' with (
  $include-spacing-modifiers: false,
  $output-text-classes: false,
  $output-visibility-classes: false
);
```

2022-07-21 07:57 UTC, ediblecode commented on gatsby/src/styles/global.scss
>  @import './settings';
Can we change these to `@use` please?

2022-07-25 08:58 UTC, ediblecode submitted a review, later dismissed

2022-08-11 13:23 UTC, johndavey72 approved these changes

2022-08-11 14:32 UTC, merged