Bnf 1238 wound management
nice-digital/bnf-gatsby pull request #60
Opened 2022-04-26 14:43 UTC by barkertron

2022-04-27 08:54 UTC, ediblecode commented on gatsby/src/pages/wound-management/index.module.scss
> +    text-transform: lowercase;
Thanks for the heads up!

2022-04-27 09:00 UTC, ediblecode requested changes

2022-04-27 09:02 UTC, barkertron commented on gatsby/src/pages/wound-management/index.test.tsx
> +describe("Medical devices index page", () => {
Ha! Evidence of some copy/paste action here

2022-04-27 10:29 UTC, ediblecode approved these changes

2022-04-27 14:15 UTC, ediblecode approved these changes

2022-05-03 08:55 UTC, ediblecode approved these changes

2022-05-03 08:56 UTC, merged