BNF-1311 Make left hand menu collapsible on mobile
nice-digital/bnf-gatsby pull request #62
Opened 2022-04-29 08:54 UTC by emollett

https://nicedigital.atlassian.net/browse/BNF-1311

2022-05-10 14:05 UTC, barkertron commented on gatsby/src/components/DetailsPageLayout/DetailsPageLayout.module.scss
> +    display: block !important;
Is there an alternative to using `!important` here - could stack up specificity instead perhaps? Something along the lines of `:global(.stacked-nav.stacked-nav)` might work and would give you the ability to apply further overrides, which `!important` would not.

2022-05-10 15:18 UTC, barkertron approved these changes

2022-05-13 13:09 UTC, ediblecode requested changes

2022-05-13 13:09 UTC, ediblecode commented on gatsby/src/pages/medical-devices/{BnfClinicalMedicalDeviceInformationGroup.medicalDeviceType__medicalDevice__slug}/{BnfClinicalMedicalDeviceInformationGroup.slug}.tsx
> -							<StackedNav
There's also a stacked nav inside {BnfMedicalDeviceType.slug}.tsx that looks like we've missed

2022-05-13 13:09 UTC, ediblecode commented on gatsby/src/components/DetailsPageLayout/DetailsPageLayout.tsx
> +							{isClient ? (
I think if we move the logic and styles into the menu component, then it'll be easier to replace all instances with the nds stacked-nav directly if/when we move the logic there.

2022-05-13 13:09 UTC, ediblecode commented on gatsby/src/components/Menu/Menu.tsx
> +	ariaLabel?: string;
If we keep the same prop types as the main stacked nav element then it'll be easier to swap out for the NDS one directly if/when we move the logic into the NDS

2022-05-20 10:16 UTC, ediblecode approved these changes

2022-05-20 10:22 UTC, merged