BNF-1209 Construct drug monograph meta description
nice-digital/bnf-gatsby pull request #78
Opened 2022-05-16 14:43 UTC by barkertron

https://nicedigital.atlassian.net/browse/BNF-1328

2022-05-16 15:18 UTC, ediblecode requested changes

2022-05-17 08:29 UTC, barkertron commented on gatsby/src/pages/drugs/{BnfDrug.slug}/index.tsx
> +		bnfDrug.renalImpairment,
Nope, it gets added on line 232 - has to be dealt with separately as we can't just use the pot name like we can with the other sections.

2022-05-17 09:31 UTC, ediblecode commented on gatsby/src/pages/drugs/{BnfDrug.slug}/index.tsx
> +		bnfDrug.renalImpairment,
Doh yeah sorry, completely missed that!

2022-05-17 09:31 UTC, ediblecode approved these changes

2022-05-18 18:37 UTC, ediblecode approved these changes

2022-05-19 12:48 UTC, ediblecode approved these changes

2022-05-19 12:51 UTC, merged